[package]
name = "8051ReverseEngineering"
description = "Some applications for reverse engineering 8051 firmware"
readme = "README.md"
version = "1.0.0"
authors = ["HectorTa1989"]
edition = "2021"
keywords = ["reverse-engineering", "8051"]
categories = ["command-line-utilities"]
license = "MIT"
repository = "https://github.com/HectorTa1989/8051ReverseEngineering"


[dependencies]
clap = "2.33"         # cl arg parsing
rustfft = "6.0"       # base address finding
nom = "6.1"           # parse libraries, init structure
num-traits = "^0.2"	  # omf51 parsing
lazy_static = "1.4.0" # for some default values
ar = "0.9"            # for sdcc library, which is an bsd ar archive
bitflags = "1.2"	  # for sdcc library
serde_json = "1.0"    # json output
serde = { version = "1.0", features = ["derive"] }
dirs = "3.0"

[dev-dependencies]
hex = "~0.4.0"		# used for omf51 tests
