---
name: Build
on:
  - push
  - pull_request
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.48
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}"
      - run: cargo test
  build:
    name: Build Binary
    needs:
      - test
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: '.exe'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: '${{ matrix.target }}'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          cargo test --target "${{ matrix.target }}" --release
          cargo build --target "${{ matrix.target }}" --release
      - run: |
          cargo install cargo-strip
          cargo strip --target "${{ matrix.target }}"
      - uses: actions/upload-artifact@v2
        with:
          name: '8051ReverseEngineering-${{ matrix.os }}'
          path: 'target/${{ matrix.target }}/release/8051ReverseEngineering${{ matrix.suffix }}'
